export enum ProgramType {
  PREGRADO = 'PREGRADO',
  POSGRADO_DIPLOMADO = 'POSGRADO-DIPLOMADO',
  POSGRADO_DOCTORADO = 'POSGRADO-DOCTORADO',
  POSGRADO_MAESTRIA = 'POSGRADO-MAESTRIA',
  POSGRADO_SEGUNDAESPECIALIDAD = 'POSGRADO-SEGUNDAESPECIALIDAD'
}
